language: haskell
ghc:
    - "7.8"

script:
    - runhaskell ./HSS_Server/test.hs checkRows
    - runhaskell ./HSS_Server/test.hs checkCols
    - runhaskell ./HSS_Server/test.hs checkCells
    - runhaskell ./HSS_Server/test.hs checkSolvedBoard
    - runhaskell ./HSS_Server/test.hs solvePossible
    - runhaskell ./HSS_Server/test.hs solveImpossible
